### ISSUE TITLE
Use schema for type conversion in MELT model/export

### ISSUE THREAD

**Issue by DanielHHowell** [cisco-open/fsoc#138]
## Problem Statement

In melt export there is an iterative attempt to convert the type passed in the yaml mock value. This can cause issues and would perhaps benefit from parsing/saving the type as defined in the entity schema on modeling. The current workaround is to use mock values that cannot be parsed into an undesired type. For example, 100.0 will get exported as an integer. 

## Proposed Solution

Capture the type in the schema and use to produce the melt model and then in export

**Comment by pavel-georgiev** [comment]
Can this be solved by using strings in the input data, i.e.
```
optimize.progress.percent: "100.0"
```

**Comment by pnickolov** [comment]
checking with the team members responsible to the melt commands

**Comment by rquedas** [comment]
We are missing a lot of documentation explaining how melt model works and how to build the yaml data file, and the assumptions aren't clear for sure.

Would that help?

**Comment by pavel-georgiev** [comment]
@rquedas the problem at hand is that fsoc does some type conversions that are not obvious. For example, if you tries to send the following field:

```
optimize.progress.percent: 100.0
```

fsoc will convert the value to an integer and send it as such. AFAIK MELT is capable of ingesting float data, so this should not be a doc issue. I see two approaches of solving this:
1. Don't do type conversion for types supported by MELT store (a float should be sent as a float). Send those as-is, convert everything else to a safe type (string?)
2. Discover the type of the field as defined by looking into the schema (we will need a network call for that) and make sure the input data is of the correct type (and fail or convert+warn if it is not)

I am in favor if (1). Note that both of these would be breaking changes - if someone is currently sending data as:
```
optimize.progress.percent: "100.0"
```
And expect this to be converted by fsoc, the changes above would result in the value send as a string, which although correct may break current uses.

**Comment by DanielHHowell** [comment]
The problem is a bit more nuanced - the export type has to exactly match the type defined in the schema for every value or the entire payload will be rejected. For approach 1) I think a type conversion must be done, otel requires it explicitly. For approach 2) I don't think a network call would be needed, currently the mocks generated via melt model are done with a provided local schema (although fetching it would be a great unrelated change). When reading the schema, an additional field of type could be appended.

Here is the exporter functionality in question:
https://github.com/cisco-open/fsoc/blob/main/platform/melt/exporter.go#L408

**Comment by rquedas** [comment]
hummm, it's hard to guarantee the type during modeling, people may mess up the yaml value and send the wrong type anyway.

It is also important to highlight that entity attribute names and the semantic convention for the resource attributes in the OTLP protobuff might be different. The mapping is represented by a resourceMapping definition and it can be quite complex which will make it hard to figure out what is the type for a given attribute.

**Comment by k-shaikh** [comment]
I think we should generically extend the platform/melt package to handle different type of attributes.

- change Attributes map[string]string from types.go to  map[string]interface{}
- change exporter.go to look at the types of value in the attribute map to decide what otel value type it should be mapped to.

The melt yaml when Unmarrshalled will create the correct types in the Attributes map value. 
I tried an example here to test this theory - https://go.dev/play/p/sVj7MfyVnA9

**Comment by pnickolov** [comment]
Fixed and coming up in the next release
