### ISSUE TITLE
`--curl` flag to print out curl cmd

### ISSUE THREAD

**Issue by ekquasar** [cisco-open/fsoc#24]
https://github.com/moul/http2curl

**Comment by ekquasar** [comment]
Usually support requests require the offending curl command, so having this feature will be a force multiplier for getting FSO support - more straightforwardly, the feature also makes it transparent that it's not e.g. a bug with fsoc itself to folks less familiar with this tool.

**Comment by pnickolov** [comment]
In progress, see PR #54

**Comment by pnickolov** [comment]
Implemented in v0.32.0. Thank you @cuichenli!
