### ISSUE TITLE
When publishing a solution, how long should it take for UI changes to take effect?

### ISSUE THREAD

**Issue by camnealie** [cisco-open/fsoc#247]
Hello - just looking to get an idea of how long I should wait between bump publishing a solution, and when I should expect to see the UI change. 

I'm making simple changes like adding a '2' to the end of my ECPHome title. That was quite a while ago (maybe 15 minutes), CLI package validation works fine, publishing was successful, I just need to know if this is a 'takes a while' kind of issue, or if there's some reason why the UI specifically wouldn't update / fail to update, while the rest of the solution install was successful.

**Comment by pnickolov** [comment]
Hello @camnealie , generally it should take a few minutes (well below 15, typically 2-3). If you see anything else, please reach out to the platform support. Fsoc's operation completes as soon as the upload returns (the `fsoc solution push`) command completes.

There are two additional things that you can do:
1. You can use the `--wait` flag (incl. use a custom timeout). This works great for the happy path and will, at least, indicate a failure if the new version does not get installed within the timeout
2. You can use the `fsoc solution status` command and compare the uploaded vs. installed version

```
$ fsoc solution status agent
                       Solution Name: agent
        Solution Subscription Status: Subscribed
     Current Solution Upload Version: 23.12.111
   Current Solution Upload Timestamp: 2023-12-07T23:37:13.709Z
     Last Successful Install Version: 23.12.111
    Current Solution Install Version: 23.12.111
Current Solution Install Successful?: true
       Current Solution Install Time: 2023-12-07T23:37:14.296Z
    Current Solution Install Message:
```

If there is a problem during installation, the last field will be non-empty and contain the installation error message.

**Comment by Neo2308** [comment]
@camnealie The templates / templatePropExtensions are cached on your browser to improve ui performance. To get rid of the cache, go to dev tools > Application > IndexedDB > Delete DB
The UI should take about a minute to load but your changes should get reflected.
