### ISSUE TITLE
--bump flag is removing "solutionType" property from manifest.json

### ISSUE THREAD

**Issue by brownkw** [cisco-open/fsoc#270]
## Description

When adding --bump to the command for pushing a solution, the "solutionType" property is being stripped from the manifest file.

## Expected Behavior

The "solutionType" property remains while the version number is bumped in manifest.json. 

## Actual Behavior

The "solutionType" property is removed from manifest.json

## Affected Version

0.58.1 (and previous versions)

## Steps to Reproduce

1. Create a solution with a manifest version of 1.1.0. Add a property called "solutionType" with a value of "component".
1. Run `fsoc solution validate --tag=dev --bump`

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by pnickolov** [comment]
Thank you @brownkw!  Fixed in v0.59.0
