### ISSUE TITLE
`fsoc solution download <solution-name>` doesn't download anything.

### ISSUE THREAD

**Issue by ekquasar** [cisco-open/fsoc#357]
## Description

For a subscribed solution, running the download command produces stderr info level logging explaining that the download is successful. But nothing is in curdir.

## Expected Behavior

Download a zip or something to curdir.

## Actual Behavior

No new artifact appears in curdir.

## Affected Version

fsoc version 0.68.1

## Steps to Reproduce

1. Subscribe to a solution
1. Try to download it
1. Nothing happens

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by pnickolov** [comment]
@ekquasar , the current behavior is that the zip file is downloaded to the parent of the current directory. This will be fixed shortly. (The workaround is to call fsoc from a non-root directory where it will be allowed to save in the parent)
