### ISSUE TITLE
Colon in solution extend add-knowledge does not handle colon (:) properly

### ISSUE THREAD

**Issue by tutnes** [cisco-open/fsoc#68]
## Description

When I run: fsoc solution extend --add-knowledge solution:solution-knowledge-name
The manifest.json is updated, and a file is created, however, the filename gets a strange name. (this is probably due to the way it handles the : which may be a difficult character in file paths

## Expected Behavior

If instead it uses the : to split and create solution as the folder underneath knowledge, and the solution-knowledge-name as the file under that path

## Actual Behavior

It creates a file with : in it

## Affected Version

fsoc version 0.31.0

## Steps to Reproduce

1. First step
Run command: fsoc solution extend --add-knowledge solution:solution-knowledge-name

## Checklist

- [ x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x ] I have verified this does not duplicate an existing issue

**Comment by pnickolov** [comment]
@tutnes thank you for reporting this, checking it out...

**Comment by pnickolov** [comment]
@tutnes sorry for the delayed response on this. My understanding is that the solution name should not be part of the type name when using --add-knowledge. We can add checks to make sure that the character set is verified and colon is disallowed with a helpful message.

**Comment by pnickolov** [comment]
Note: PR #163 adds a check and a clarifying error message. Thank you @tutnes for pointing this out!
