### ISSUE TITLE
fsoc solution push --wait hangs

### ISSUE THREAD

**Issue by ekquasar** [cisco-open/fsoc#92]
I ran `fsoc solution push --wait` and it is repeatedly trying:
```
...
✓ Platform API call (GET /objstore/v1beta/objects/extensibility:solutionInstall?order=desc&filter=data.solutionName+eq+%22optimize-test-templating%22+and+data.solutionVersion+eq+%221.0.128%22&max=1)                      
✓ Platform API call (GET /objstore/v1beta/objects/extensibility:solutionInstall?order=desc&filter=data.solutionName+eq+%22optimize-test-templating%22+and+data.solutionVersion+eq+%221.0.128%22&max=1) 
...
```

but the `fsoc solution list` shows my solution is already installed.

**Comment by cuichenli** [comment]
the solution listed in `fsoc solution list` actually does not mean the solution has been successfully installed. instead you may want to check with the command `fsoc solution status`.

**Comment by ekquasar** [comment]
true enough - thanks vm, that's sufficient to invalidate this bug report
